on: [push, pull_request]
name: Anon ShellCheck
jobs:
  konstruktoidShellCheck:
    name: Anon ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Anon ShellCheck
        uses: ./action-shellcheck
      - name: Create Issue
        if: failure()
        uses: JasonEtco/create-an-issue@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
