name: mycheck
on:
  
  push:
    branches:
      - master
  pull_request:
    
jobs:
  myshellcheck:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Lint check
      uses: azohra/shell-linter@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
