name: ShellerCeck
on:
  branches:
    - master
  pull_request:

jobs:
  Sheller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint check
        uses: azohra/shell-linter@v0.3.0
